version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        image: danilosoftwares/bikeserverprocessador:latest
        restart: always
        links:
            - "db"
        ports:
            - "5000:5000"
        depends_on:
            - db            