services:
    db:
        platform: linux/x86_64
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        image: danilosoftwares/bikeserverprocessador:latest
        restart: always
        links:
            - "db"
        ports:
            - "5001:5000"
        depends_on:
            - db       
    # python-app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5001:5000"
    #     environment:
    #         - PYTHONUNBUFFERED=1
    #     volumes:
    #         - .:/usr/src/app  